export const PROFILS = {
  NUL: "NUL",
  ANTENNE: "ANTENNE",
  SECTEUR: "SECTEUR",
  NATIONAL_LECTURE: "NATIONAL_LECTURE",
  NATIONAL_COMPLET: "NATIONAL_COMPLET",
  NATIONAL_PLUS: "NATIONAL_PLUS",
  ADMINISTRATEUR: "ADMINISTRATEUR",
}